spring.application.name=Mylibrary

## Server port (default is 8080)
server.port=8081

# Database Info
spring.datasource.url=jdbc:mysql://mysql-docker:3306/library
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Jpa Info
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## DevTools auto reloads
#spring.devtools.livereload.enabled=true
#spring.devtools.restart.enabled=true